apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: jp-test-course
spec:
  # build:
  #   secrets:
  #     - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "41652af1-ee1d-4cdb-9794-a89456304718"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET